import os, sys

def combine(    output,
                files,
                autogen_header='\n/* FILE AUTOGENERATED BY %s */',
                autogen_define='\n#define PACKAGED',
                file_header='\n\n/* SOURCE FILE: %s */\n\n'):
    
    o = open(output, 'w')
    o.write(autogen_header % (__name__))
    o.write(autogen_define)
    
    for f in files:
        i = open(f, 'r')
        o.write(file_header % (f))
        o.write(i.read())
    
    o.flush()
    o.close()
